use_frameworks!

platform :ios, '10.0'

target 'FFTextView_Example' do
  pod 'FFTextView', :path => '../'

  pod 'Masonry'
  
  target 'FFTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
